version: "3"
services:
  go:
    build:
      context: ../
      dockerfile: .devcontainer/infra/go/Dockerfile
    env_file:
      - .env
    tty: true
    ports:
      - ${GO_PORT}:${GO_PORT}
    volumes:
      - ../:/data
      - ~/.gitconfig:/root/.gitconfig
    security_opt: # delve用に必要
      - apparmor:unconfined
    cap_add: # delve用に必要
      - SYS_PTRACE